package com.codealpha.chatbot.model;

import com.codealpha.chatbot.nlp.SentimentAnalyzer.SentimentResult;
import java.util.ArrayList;
import java.util.List;

/**
 * Encapsulates the response generated by the chatbot engine,
 * including NLP diagnostics, confidence scores, extracted entities, and quick suggestions.
 */
public class BotResponse {
    private final String text;
    private final Intent intent;
    private final double confidence;
    private final SentimentResult userSentiment;
    private final String algorithmUsed;
    private final List<String> extractedEntities;
    private final List<String> suggestedChips;
    private final long responseTimeMs;

    public BotResponse(String text, Intent intent, double confidence, SentimentResult userSentiment,
                       String algorithmUsed, List<String> extractedEntities,
                       List<String> suggestedChips, long responseTimeMs) {
        this.text = text;
        this.intent = intent != null ? intent : Intent.UNKNOWN_FALLBACK;
        this.confidence = confidence;
        this.userSentiment = userSentiment;
        this.algorithmUsed = algorithmUsed != null ? algorithmUsed : "Rule/Heuristic";
        this.extractedEntities = extractedEntities != null ? extractedEntities : new ArrayList<>();
        this.suggestedChips = suggestedChips != null ? suggestedChips : new ArrayList<>();
        this.responseTimeMs = responseTimeMs;
    }

    public String getText() { return text; }
    public Intent getIntent() { return intent; }
    public double getConfidence() { return confidence; }
    public SentimentResult getUserSentiment() { return userSentiment; }
    public String getAlgorithmUsed() { return algorithmUsed; }
    public List<String> getExtractedEntities() { return extractedEntities; }
    public List<String> getSuggestedChips() { return suggestedChips; }
    public long getResponseTimeMs() { return responseTimeMs; }
}
